<h1> Quiz 1 Pemahaman tentang Model Selection</h1>

Jelaskan dengan bahasa kalian sendiri

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kira2 kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

### jawab
1. bias dan variance merupakan 2 jenis error yang ada pada model. bias terjadi karena model terlalu simpel sedangkan variance terjadi karena model terlalu kompleks
2. Underfit terjadi ketika model terlalu sederhana dan tidak mampu untuk menyesuaikan pola yang terdapat pada data latih (train score & test score rendah) sedangkan Overfitting terjadi ketika model terlalu memiliki prediksi yang sangat baik pada data training, namun prediksinya buruk pada data testing
3. hyperparameter tuning
4. tidak overfitting maupun underfitting
5. tergantung pada jumlah hyperparameter & kekuatan komputasi komputer yang dimiliki

<h1> Quiz 2 Praktis Model Selection</h1>

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik atau overtting atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut : https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [2]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [4]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [9]:
# 1 
from sklearn.model_selection import train_test_split

X = df.drop('survival_status', axis= 1)
y = df['survival_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 21, stratify= y)

In [10]:
# 2 - 6
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

model_knn = KNeighborsClassifier()
param_grid = {
    'n_neighbors': np.arange(5, 30),
    'weights': ['uniform', 'distance']
}
gscv = GridSearchCV(model_knn, param_grid, cv=10, scoring= 'roc_auc')
gscv.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29]),
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [11]:
# 7
gscv.best_params_

{'n_neighbors': 8, 'weights': 'distance'}

In [12]:
# 8
gscv.best_score_

0.7094012605042017

In [13]:
# 9
y_pred_prob = gscv.predict_proba(X_test)

In [16]:
y_pred_prob

array([[0.8396757 , 0.1603243 ],
       [0.79116585, 0.20883415],
       [0.63461558, 0.36538442],
       [0.        , 1.        ],
       [0.67722631, 0.32277369],
       [1.        , 0.        ],
       [0.53363999, 0.46636001],
       [0.72937691, 0.27062309],
       [0.85437329, 0.14562671],
       [0.67722631, 0.32277369],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.72819477, 0.27180523],
       [1.        , 0.        ],
       [0.84156107, 0.15843893],
       [0.64093838, 0.35906162],
       [0.85534297, 0.14465703],
       [0.68644891, 0.31355109],
       [1.        , 0.        ],
       [0.46625569, 0.53374431],
       [0.55174594, 0.44825406],
       [0.84156107, 0.15843893],
       [1.        , 0.        ],
       [0.34594814, 0.65405186],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.6520165 , 0.3479835 ],
       [0.58875063, 0.41124937],
       [0.54027675, 0.45972325],
       [0.75282578, 0.24717422],
       [1.

In [15]:
gscv.classes_

array([1, 2], dtype=int64)

In [18]:
# 10
y_pos_pred = y_pred_prob[:, 1]
y_pos_pred

array([0.1603243 , 0.20883415, 0.36538442, 1.        , 0.32277369,
       0.        , 0.46636001, 0.27062309, 0.14562671, 0.32277369,
       1.        , 0.        , 0.27180523, 0.        , 0.15843893,
       0.35906162, 0.14465703, 0.31355109, 0.        , 0.53374431,
       0.44825406, 0.15843893, 0.        , 0.65405186, 0.        ,
       0.        , 0.3479835 , 0.41124937, 0.45972325, 0.24717422,
       0.        , 1.        , 0.23923218, 0.09089058, 0.73488259,
       0.22442009, 0.12260191, 0.10427116, 0.43376177, 0.22107108,
       0.49051021, 0.4417585 , 0.27955334, 0.4618577 , 0.13815895,
       0.        , 0.        , 0.08888316, 0.13430542, 0.88106452,
       0.27734122, 0.51159375, 0.4652136 , 0.11246145, 0.49222287,
       0.        , 0.19253033, 0.39296917, 0.        , 0.88783049,
       0.39574849, 0.25320622, 0.12170658, 0.        , 0.26178135,
       0.13697051, 0.34473297, 0.11447661, 0.63332535, 0.        ,
       0.65799749, 0.263332  , 0.        , 0.86724282, 0.26461

In [19]:
# 11
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_pos_pred)

0.6166666666666667

In [ ]:
# 12 model overfitting

In [22]:
# 13 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV

model_dt = DecisionTreeClassifier()
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': np.arange(1,3),
    'min_samples_split': np.arange(2, 100, 20),
    'max_features': np.arange(1, 3),
    'class_weight': [{1: x, 2: 1-x} for x in np.arange(0.1, 0.99, 0.1)]
}

rscv = RandomizedSearchCV(model_dt, param_grid, cv= 10, scoring='roc_auc', n_iter=50)
rscv.fit(X_train, y_train)

RandomizedSearchCV(cv=10, error_score=nan,
                   estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort='deprecated',
                                                    random_state=None,
         

In [24]:
rscv.best_score_

0.6746586134453783

In [25]:
rscv.best_params_

{'min_samples_split': 42,
 'max_features': 2,
 'max_depth': 2,
 'criterion': 'gini',
 'class_weight': {1: 0.2, 2: 0.8}}

In [ ]:
y_pos_pred = rscv.predict_proba(X_test)[:,1]